### ISSUE TITLE
Cannot log in

### ISSUE THREAD

**Issue by Spl01ter** [oneatletico/cmd-wechat-terminal#3]
Your wechat account may be LIMITED to log in WEB wechat, error info:
<error><ret>1203</ret><message>For account security, newly registered WeChat accounts are unable to log in to WeChat for Web. To use WeChat on a computer, you can download WeChat for Windows or WeChat for Mac at http://wechat.com</message></error>
Start auto replying.

**Comment by lukiiiz22** [comment]
Thanks for the feedback. It seems that Tencent updated their policy to limit WeChat web login.
I am going to check it.

**Comment by Spl01ter** [comment]
It seems like Tencent has restricted any accounts created after 2017 from using WeChat web. There is no API for WeChat Windows or Mac. I think there is no fix for this.
